### ISSUE TITLE
empty catch block - not accepted by some linters

### ISSUE THREAD

**Issue by rejoyprem** [fasttime/Polytype#8]
theres an empty catch block in **polytype.cjs** file at **line 526,** it works fine without issues but some linters are now allowing it to be uploaded to proxy repos. can we add a simple command to handle the exception?

**Comment by fasttime** [comment]
Hi @rejoyprem, could you please tell us what linters are affected?

**Comment by fasttime** [comment]
Closing after one year of inactivity. Feel free to open a new issue if you feel that this problem still needs to be discussed.
